import { NextResponse } from "next/server";
import { PrismaClient } from "@prisma/client";
import fs from "fs";
import path from "path";

const prisma = new PrismaClient();
const VPN_DATA_PATH = "/vpn_data/chap-secrets";

// Helper function to sync L2TP configs to shared docker volume
export async function syncChapSecrets() {
  try {
    if (!fs.existsSync("/vpn_data")) {
      console.log("[VPN] Skipping chap-secrets sync: /vpn_data volume not found (likely running outside docker).");
      return;
    }

    const accounts = await prisma.vpnAccount.findMany({
      where: { type: "L2TP", isActive: true },
    });

    let chapContent = "# Automatically generated by AIBILL System\n# DO NOT EDIT MANUALLY\n\n";
    accounts.forEach((acc) => {
      // Force wildcard IP to prevent pppd pool conflicts
      chapContent += `"${acc.username}" l2tpd "${acc.password}" *\n`;
    });

    fs.writeFileSync(VPN_DATA_PATH, chapContent, "utf8");
    console.log(`[VPN] Synced ${accounts.length} L2TP accounts to ${VPN_DATA_PATH}`);
  } catch (error) {
    console.error("[VPN] Error syncing chap-secrets:", error);
  }
}

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const type = searchParams.get('type');
    
    let where = {};
    if (type) where = { type };

    const accounts = await prisma.vpnAccount.findMany({
      where,
      orderBy: { createdAt: "desc" },
    });

    return NextResponse.json(accounts);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { username, password, staticIp, type, notes } = body;

    if (!username || !password) {
      return NextResponse.json({ error: "Username and password are required" }, { status: 400 });
    }

    const newAccount = await prisma.vpnAccount.create({
      data: {
        username,
        password,
        staticIp: staticIp || null,
        type: type || "L2TP",
        notes,
        isActive: true,
      },
    });

    await syncChapSecrets();

    return NextResponse.json(newAccount);
  } catch (error: any) {
    if (error.code === 'P2002') {
      return NextResponse.json({ error: "Username or Static IP already exists" }, { status: 400 });
    }
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
