import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NexaRadius",
  description: "Generated by NexaRadius",
};

const themeScript = `(() => {
  try {
    const storedTheme = localStorage.getItem('theme') || 'dark';
    const storedDensity = localStorage.getItem('theme-density') || 'spacious';
    const storedGlass = localStorage.getItem('theme-glassmorphic') || 'disabled';
    const storedSidebar = localStorage.getItem('theme-sidebar') || 'solid';
    
    document.documentElement.classList.toggle('dark', storedTheme !== 'light');
    document.documentElement.dataset.theme = storedTheme;
    document.documentElement.dataset.density = storedDensity;
    document.documentElement.dataset.glassmorphic = storedGlass;
    document.documentElement.dataset.sidebar = storedSidebar;
  } catch (_) {
  }
})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
