import { NextResponse } from "next/server";
import { PrismaClient } from "@prisma/client";
import fs from "fs";

const prisma = new PrismaClient();
const VPN_DATA_PATH = "/vpn_data/chap-secrets";

// Helper function to sync L2TP configs
async function syncChapSecrets() {
  try {
    if (!fs.existsSync("/vpn_data")) return;

    const accounts = await prisma.vpnAccount.findMany({
      where: { type: "L2TP", isActive: true },
    });

    let chapContent = "# Automatically generated by NexaRadius System\n# DO NOT EDIT MANUALLY\n\n";
    accounts.forEach((acc) => {
      const ip = acc.staticIp ? `"${acc.staticIp}"` : "*";
      chapContent += `"${acc.username}" * "${acc.password}" ${ip}\n`;
    });

    fs.writeFileSync(VPN_DATA_PATH, chapContent, "utf8");
  } catch (error) {
    console.error("[VPN] Error syncing chap-secrets:", error);
  }
}

export async function PUT(request: Request, { params }: { params: { id: string } | Promise<{ id: string }> }) {
  try {
    const resolvedParams = await params;
    const body = await request.json();
    
    // Ignore `id` and `createdAt` from body if present
    const { id, createdAt, updatedAt, ...updateData } = body;

    const updatedAccount = await prisma.vpnAccount.update({
      where: { id: resolvedParams.id },
      data: updateData,
    });

    await syncChapSecrets();

    return NextResponse.json(updatedAccount);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function DELETE(request: Request, { params }: { params: { id: string } | Promise<{ id: string }> }) {
  try {
    const resolvedParams = await params;
    await prisma.vpnAccount.delete({
      where: { id: resolvedParams.id },
    });

    await syncChapSecrets();

    return NextResponse.json({ success: true });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
